# -*- coding: utf-8 -*-
"""Billbot.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZm8OQCx59n1FytDKF09t4ykqYLpZAWh
"""

pip install pandas fpdf yagmail openpyxl

import pandas as pd
from fpdf import FPDF
from datetime import date
import yagmail

# --- CONFIGURATION ---
SENDER_EMAIL = "mohamedapsar769@gmail.com"
SENDER_PASSWORD = "yzje usbu ogsb nmzv"  # Use Gmail App Password
SUPPORT_EMAIL = "support@wifibillbot.com"
COMPANY_NAME = "WiFiBillBot"
TODAY = date.today()
MONTH_YEAR = TODAY.strftime("%b-%Y")  # e.g., Jun-2025

# Setup email client
yag = yagmail.SMTP(SENDER_EMAIL, SENDER_PASSWORD)

# Read customer data
df = pd.read_excel("clients.xlsx")

# Loop through each customer
for i, row in df.iterrows():
    name = row["Name"]
    email = row["Email"]
    plan = row["Plan"]
    price = row["Price"]
    paid = str(row["Paid?"]).strip().lower()

    # Generate invoice number
    invoice_no = f"WBB{TODAY.strftime('%Y%m%d')}{i+1:03}"
    pdf_filename = f"Invoice_{name.replace(' ', '_')}_{MONTH_YEAR}.pdf"

    # --- Generate PDF Invoice ---
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "INTERNET BILL INVOICE", ln=True, align="C")
    pdf.set_font("Arial", '', 12)
    pdf.ln(5)

    pdf.cell(0, 10, f"Invoice No: {invoice_no}", ln=True)
    pdf.cell(0, 10, f"Billing Month: {MONTH_YEAR}", ln=True)
    pdf.cell(0, 10, f"Date: {TODAY.strftime('%d-%m-%Y')}", ln=True)
    pdf.ln(5)

    pdf.cell(0, 10, f"Customer Name: {name}", ln=True)
    pdf.cell(0, 10, f"Plan: {plan}", ln=True)
    pdf.cell(0, 10, f"Amount: Rs. {price}", ln=True)
    pdf.ln(10)



    # --- Email Content ---
    if paid == "yes":
        subject = f"[Receipt] Payment Received – {MONTH_YEAR}"
        body = f"""
Dear {name},

We’re pleased to confirm that we’ve received your payment of Rs.{price} for the {plan} plan for the billing month {MONTH_YEAR}.

Your invoice is attached for your records.

If you have any questions, feel free to reach out to our support team.

Warm regards,
Billing Team
{COMPANY_NAME} – Simplifying Internet Billing
"""
    else:
        subject = f"[Invoice] Payment Due – {MONTH_YEAR} Billing Cycle"
        body = f"""
Dear {name},

This is a reminder that your internet subscription for the {plan} plan remains unpaid for the month of {MONTH_YEAR}. The amount due is Rs.{price}.

Please find your invoice attached to this email.

We kindly request you to complete the payment at your earliest convenience to avoid service interruption.

If you have already paid, please ignore this message.

Sincerely,
Billing Team
{COMPANY_NAME} – Reliable Internet, On Time Billing
"""

    # --- Send Email with Attachment ---
    yag.send(to=email, subject=subject, contents=body, attachments=pdf_filename)

print("✅ All emails and invoices sent successfully.")